apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderbook-deployment
  labels:
    app: orderbook-deployment
spec:
  selector:
    matchLabels:
      app: orderbook-app
  replicas: 1
  template:
    metadata:
      labels:
        app: orderbook-app
    spec:
      containers:
        - name: orderbook
          image: n3m6/orderbook:latest
          imagePullPolicy: Always
          env:
            - name: ORDERBOOK_PORT
              valueFrom:
                configMapKeyRef:
                  name: haru-envs
                  key: ORDERBOOK_PORT
            - name: ORDERBOOK_GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: haru-envs
                  key: ORDERBOOK_GRPC_PORT
            - name: ORDERBOOK_WS_PORT
              valueFrom:
                configMapKeyRef:
                  name: haru-envs
                  key: ORDERBOOK_WS_PORT
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: orderbook-service
  labels:
    app: orderbook-service
spec:
  selector:
    app: orderbook-app
  type: LoadBalancer
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 4000
      name: http-port
    - protocol: TCP
      port: 8082
      targetPort: 4002
      name: wss-port

